// app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import KBarWrapper from "./kbar-wrapper";
import { RootStoreProvider } from "@/models";
import { RootStoreProviderWrapper } from "@/hooks/root-store-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Talkhealing",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <RootStoreProviderWrapper>
        <KBarWrapper>
          {children}
        </KBarWrapper>
        </RootStoreProviderWrapper>
      </body>
    </html>
  );
}
